11.x beta ng13
gentics/gentics-ui-core pull request #103
Opened 2022-05-09 14:11 UTC by pschulzk

Update to Angular 13

2022-05-13 11:02 UTC, netwarex requested changes
I have added some points need to be checked.

Also in local development mode it starts up in production, which should be checked too.

There are a lot's of Foundation Site deprecation error messages, maybe we should make a new ticket on this to investigate it in a hotfix ticket later.

The same could apply to the unit tests, as we should sometime re-enable them.

2022-06-28 13:32 UTC, pschulzk commented on projects/gentics-ui-core/tsconfig.lib.json
> +    "enableIvy": false
Yes, there were Ivy issues within consuming dependency structures.

2022-06-28 15:54 UTC, pschulzk commented on projects/gentics-ui-core/package.json
> +    "foundation-sites": "~6.5.3"
Done

2022-06-29 12:20 UTC, pschulzk commented on package.json
> +    "@angular-devkit/build-ng-packagr": "^0.1002.4",
Cannot identify flaws in build configuration.

2022-06-29 13:22 UTC, pschulzk commented on src/components/modal/modal.service.spec.ts
> +        xit('displays a title and body',
Re-enabled unit-test.

2022-06-30 09:38 UTC, merged